UKMusicLibProject/Controllers/ArtistController.cs
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Services.Repository;
using System.IO;
using UKMusicLibProject.DTO;
using UKMusicLibProject.Models;

namespace UKMusicLibProject.Controllers
{
  
    public class ArtistController : Controller
    {
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment;
        HttpClient _client;
        IConfiguration configuration;
        private readonly IArtistRepository _artistService;
        public ArtistController(IArtistRepository artistService, IConfiguration _configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment environment)
        {
            this._artistService = artistService;

            configuration = _configuration;
            string apiAddress = configuration["ApiAddress"];
            Uri baseAddress = new Uri(apiAddress);
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
            _environment = environment;

        }
        public async Task<IActionResult> Index()
        {
            List<ArtistViewModel> model = new List<ArtistViewModel>();
            HttpResponseMessage res = await _client.GetAsync("api/ArtistAPI/ListArtists");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<List<ArtistViewModel>>(result).ToList();
            }

            return View(model);
        }

        [HttpGet("ListArtist")]
        public async Task<ActionResult> ListArtist()
        {
            List<ArtistViewModel> model = new List<ArtistViewModel>();
            HttpResponseMessage res = await _client.GetAsync("api/ArtistAPI/ListArtists");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<List<ArtistViewModel>>(result).ToList();
            }
            model.ForEach(x => GetImageFromByteArray(x));
            return View(model);

        }


        [HttpGet("ArtistDetail")]
        public async Task<ActionResult> ArtistDetail(int id)
        {
            ArtistViewModel model = new ArtistViewModel();
            HttpResponseMessage res = await _client.GetAsync("api/ArtistAPI/SingleArtist?id="+id);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<ArtistViewModel>(result);
            }
            GetImageFromByteArray(model);
            return View(model);

        }

        public void GetImageFromByteArray(ArtistViewModel model)
        {
            try
            {
                if (model.ArtistPhoto != null && model.ArtistPhoto.Length > 0)
                {
                    //string wwwPath = this._environment.WebRootPath;
                    ////string contentPath = this._environment.ContentRootPath;
                    //// Generate a unique file name
                    //var fileName = Guid.NewGuid().ToString() + ".png";

                    //// Define the path to save the file
                    //var filePath = Path.Combine(wwwPath, "TempImage", fileName);

                    // Convert image to byte array

                    //Convert byte arry to base64string
                    string imreBase64Data = Convert.ToBase64String(model.ArtistPhoto);
                    string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                    //System.IO.File.WriteAllBytes(filePath, model.ArtistPhoto);
                    //model.UploadedFilePath= filePath;
                    model.ImageDataUrl= imgDataURL;
                }
            }
            catch { 
            
            }
        }

        [HttpGet]
        public ActionResult AddArtist()
        {
            GetMasterData();
            //model.PhotoPath = "Dummy Path";
            return View();

        }

        void GetMasterData()
        {
            ViewBag.Gender = new SelectList(GetGender(), "id", "value");
            ViewBag.Relationship = new SelectList(GetRelationship(), "id", "value");
            ViewBag.Profession = new SelectList(GetProfession(), "id", "value");
            ViewBag.Country = new SelectList(GetCountry(), "id", "value");

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddArtist(ArtistViewModel model)
        {
            bool isSaved = false;
            GetMasterData();
            UploadImage(model);
            ModelState.Clear();
            if (TryValidateModel(model))
            {

                ArtistDTO artist = new ArtistDTO()
                {
                    ArtistId = model.ArtistId,
                    //Age = model.Age,
                    ArtistName = model.ArtistName,
                    //Awards = model.Awards,
                    //BirthPlace = model.BirthPlace,
                    //College = model.College,
                    CurrentLocation = model.CurrentLocation,
                    //Debut = model.Debut,
                    //DOB = model.DOB,
                    //Email = model.Email,
                    //Gender = model.Gender,
                    //Hobbies = model.Hobbies,
                    LongDescription = model.LongDescription,
                    //MaritalStatus = model.MaritalStatus,
                    //Nationality = model.Nationality,
                    //NetWorth = model.NetWorth,
                    //PhoneNo = model.PhoneNo,
                   // PhotoPath = model.PhotoPath,
                    //Profession = model.Profession,
                    //Salary = model.Salary,
                    //School = model.School,
                    ShowInFront = model.ShowInFront,
                    ShowInFrontOrder = model.ShowInFrontOrder,
                    SortDescription = model.SortDescription,
                    //ArtistPic = model.ArtistPic,
                    Country = model.Country,
                   
                    Age = model.Age,
                    ArtistPhoto =model.ArtistPhoto,
                    Gender = model.Gender
                };

                HttpResponseMessage response = await _client.PostAsJsonAsync("api/ArtistAPI/CreateArtist", artist);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("ListArtists");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server Error try after some time");
                    return View(model);

                }

            }
            return View(model);
        }


        void UploadImage(ArtistViewModel model)
        {
            IFormFile file = model.ArtistPic;
            if (file != null && file.Length > 0)
            {
                // Check if the file is an image
                if (IsImageFile(file))
                {

                    //string wwwPath = this._environment.WebRootPath;
                    ////string contentPath = this._environment.ContentRootPath;
                    //// Generate a unique file name
                    //var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    //// Define the path to save the file
                    //var filePath = Path.Combine(wwwPath, "TempImage", fileName);

                    // Save the file
                    //using (var stream = new FileStream(filePath, FileMode.Create))
                    //{
                    //    file.CopyToAsync(stream);
                    //    model.UploadedFilePath = filePath;
                    //}

                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.CopyTo(ms);
                        model.ArtistPhoto = ms.ToArray();
                        model.UploadedFilePath = "Valid path";
                    }
                }
                else
                {
                    model.ArtistPhoto = null;
                    //model.UploadedFilePath = string.Empty;
                }
            }
            else
            {
                //todo if already uploaded image file use that file to insert or update
                model.ArtistPhoto = null;
                //model.UploadedFilePath = string.Empty;
            }
        }

        private bool IsImageFile(IFormFile file)
        {
            // Check if the file has a valid image file extension
            var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif" };
            var fileExtension = Path.GetExtension(file.FileName).ToLowerInvariant();
            return allowedExtensions.Contains(fileExtension);
        }
        public static Byte[] ToByteArray(Stream stream)
        {
            Int32 length = stream.Length > Int32.MaxValue ? Int32.MaxValue : Convert.ToInt32(stream.Length);
            Byte[] buffer = new Byte[length];
            stream.Read(buffer, 0, length);
            return buffer;
        }

        [HttpGet("LoadArtist")]
        public ActionResult UpdateArtist(int id)
        {
            ArtistViewModel model = new ArtistViewModel();
            var res = _client.GetAsync("api/ArtistAPI/SingleArtist/" + id).Result;
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<ArtistViewModel>(result);
            }

            ViewBag.Gender = new SelectList(GetGender(), "id", "value");
            ViewBag.Relationship = new SelectList(GetRelationship(), "id", "value");
            ViewBag.Profession = new SelectList(GetProfession(), "id", "value");
            ViewBag.Country = new SelectList(GetCountry(), "id", "value");
            return View(model);

        }

UKMusicLibProject/Controllers/ContractController.cs
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Services.Repository;
using UKMusicLibProject.DTO;
using UKMusicLibProject.Models;


namespace UKMusicLibProject.Controllers
{
    public class ContractController : Controller
    {
        HttpClient _client;
        IConfiguration configuration;
        public readonly IContractRepository iContractRepository;
        public ContractController(IContractRepository _iContractRepository,
             IConfiguration _configuration)
        {
            iContractRepository = _iContractRepository;
            configuration = _configuration;
            string apiAddress = configuration["ApiAddress"];
            Uri baseAddress = new Uri(apiAddress);
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        public async Task<IActionResult> Index()
        {
            List<ContractViewModel> model = new List<ContractViewModel>();
            HttpResponseMessage res = await _client.GetAsync("api/Contract/ContractList");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<List<ContractViewModel>>(result);
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult AddContract()
        {
            ContractViewModel model = new ContractViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddContract(ContractViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _client.PostAsJsonAsync("api/Contract/CreateContract", model);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }

            }
            return View(model);
        }



    }
}

UKMusicLibProject/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UKMusicLibProject.DTO;
using UKMusicLibProject.Models;

namespace UKMusicLibProject.Controllers
{
    public class UserController : Controller
    {
        HttpClient _client;
        IConfiguration configuration;
        public UserController(IConfiguration _configuration)
        {
            configuration = _configuration;
            string apiAddress = configuration["ApiAddress"];
            Uri baseAddress = new Uri(apiAddress);
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        public async Task<IActionResult> Index()
        {
            List<UserViewModel> model = new List<UserViewModel>();
            HttpResponseMessage res = await _client.GetAsync("api/UserAPI/ListUsers");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<List<UserViewModel>>(result);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string empSearch)
        {
            List<UserViewModel> model = new List<UserViewModel>();
            HttpResponseMessage res = await _client.GetAsync("api/UserAPI/ListUsers");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<List<UserViewModel>>(result).ToList();
            }
            ViewData["UserDetail"] = empSearch;

            if (!string.IsNullOrEmpty(empSearch))
            {
                model = model.Where(x => x.FirstName.Contains(empSearch)).ToList();
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult AddUser()
        {
            UserViewModelCreate model = new UserViewModelCreate();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddUser(UserViewModelCreate model)
        {
            if (ModelState.IsValid)
            {
                UserDToCreate objUserDToCreate = new UserDToCreate()
                {
                    Id = model.UserId,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    ContactNo = model.ContactNo,
                    Address = model.Address,
                    Password = model.Password,
                    UserName = model.UserName
                };
                var response = await _client.PostAsJsonAsync("api/UserAPI/CreateUser", objUserDToCreate);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("RegistrationSuccess");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }

            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(int? id)
        {
            UserViewModel model = new UserViewModel();
            string url = "api/UserAPI/SingleUser?id=";
            using (var response = await _client.GetAsync(url + id))
            {
                var result = response.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<UserViewModel>(result);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(UserViewModel model)
        {
            //HttpClient client = _api.Initial();
            string url = "api/UserAPI/UpdateUser";
            if (ModelState.IsValid)
            {
                var response = await _client.PutAsJsonAsync(url, model);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }

            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            UserViewModel model = new UserViewModel();
            string url = "api/UserAPI/SingleUser?id=";
            using (var response = await _client.GetAsync(url + id))
            {
                var reult = response.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<UserViewModel>(reult);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            UserViewModel model = new UserViewModel();
            string url = "api/UserAPI/SingleUser?id=";
            using (var response = await _client.GetAsync(url + id))
            {
                var reult = response.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<UserViewModel>(reult);
            }

            return View(model);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            string url = "api/UserAPI/DeleteUser?id=";
            await _client.DeleteAsync(url + id);

            return RedirectToAction("Index");
        }



        [HttpGet]
        public async Task<IActionResult> RegistrationSuccess()
        {
            
            return View();
        }

    }
}

UKMusicLibProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UKMusicLibProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UKMusicLibProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UKMusicLibProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UKMusicLibProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UKMusicLibProject/Views/Shared/_Layout_Login.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
   
    <title>@ViewData["Title"] - UKMusicLibProject</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/UKMusicLibProject.styles.css" asp-append-version="true" />


    <link rel="icon" href="~/favicon.png" type="image/png">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    <link href="~/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/css/animate.css" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
        <script src="js/respond-1.1.0.min.js"></script>
        <script src="js/html5shiv.js"></script>
        <script src="js/html5element.js"></script>
    <![endif]-->

</head>
<body>
  
    <!--Header_section-->
    @RenderBody()


   

    <script type="text/javascript" src="~/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/jquery-scrolltofixed.js"></script>
    <script type="text/javascript" src="~/js/jquery.nav.js"></script>
    <script type="text/javascript" src="~/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="~/js/jquery.isotope.js"></script>
    <script src="~/js/fancybox/jquery.fancybox.pack.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/wow.js"></script>
    <script type="text/javascript" src="~/js/custom.js"></script>
   @* <script src="~/lib/jquery/dist/jquery.min.js"></script>*@
  @*  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UKMusicLibProject/Views/Shared/_Layout_New.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
   
    <title>@ViewData["Title"] - UKMusicLibProject</title>
   @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/UKMusicLibProject.styles.css" asp-append-version="true" />


    <link rel="icon" href="~/favicon.png" type="image/png">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    <link href="~/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/css/animate.css" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
        <script src="js/respond-1.1.0.min.js"></script>
        <script src="js/html5shiv.js"></script>
        <script src="js/html5element.js"></script>
    <![endif]-->

</head>
<body>
    <!--Header_section-->
    <header id="header_wrapper">
        <div class="container">
            <div class="header_box">
                <!--<div class="logo"><a href="#">Resume</a></div>-->
                <nav class="navbar navbar-inverse" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                    </div>
                    <div id="main-nav" class="collapse navbar-collapse navStyle">
                        <ul class="nav navbar-nav" id="mainNav">
                            <li class="active"><a  asp-area="" asp-controller="Artist" asp-action="Index" class="scroll-link">Home</a></li>
                            @*<li class=""><a href="#carousel" class="scroll-link">Artist</a></li>*@
                            <li class=""><a class="" asp-area="" asp-controller="Artist" asp-action="ListArtist">Artist</a></li>
                            <li><a asp-area="" asp-controller="Concert" asp-action="Index" class="scroll-link">Concert</a></li>
                            <li><a asp-area="" asp-controller="Contract" asp-action="Index" class="scroll-link">Contract</a></li>
                            <li><a asp-area="" asp-controller="" asp-action="" class="scroll-link">Upcoming concert</a></li>
                            <li><a asp-area="" asp-controller="User" asp-action="Index" class="scroll-link">User</a></li>
                           @* <li><a href="#experience" class="scroll-link">Awards</a></li>*@
                            <li><a asp-area="" asp-controller="" asp-action="ListArtist" class="scroll-link">Contact</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!--Header_section-->
    @RenderBody()


   

    <script type="text/javascript" src="~/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/jquery-scrolltofixed.js"></script>
    <script type="text/javascript" src="~/js/jquery.nav.js"></script>
    <script type="text/javascript" src="~/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="~/js/jquery.isotope.js"></script>
    <script src="~/js/fancybox/jquery.fancybox.pack.js" type="text/javascript"></script>
    <script type="text/javascript" src="~/js/wow.js"></script>
    <script type="text/javascript" src="~/js/custom.js"></script>
   @* <script src="~/lib/jquery/dist/jquery.min.js"></script>*@
  @*  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>